# Database
mysql:
  name: 'table'
  user: 'root'
  password: 'password'
# Economy settings
economy:
  # Amount of coins player get when join server for first time
  coins: 0
  # Default limit of coins player can store in bank
  limit: 2000000
# Gui settings
gui:
# Npc settings
npc: